development:
  adapter: sqlite3
  database: barbershop.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: test_barbershop.db
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: production_barbershop.db
  pool: 5
  timeout: 5000
